// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gjbastidas/GoSimpleAPIWithMongoDB/models (interfaces: Post)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/gjbastidas/GoSimpleAPIWithMongoDB/models"
	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	mongo "go.mongodb.org/mongo-driver/mongo"
)

// MockPost is a mock of Post interface.
type MockPost struct {
	ctrl     *gomock.Controller
	recorder *MockPostMockRecorder
}

// MockPostMockRecorder is the mock recorder for MockPost.
type MockPostMockRecorder struct {
	mock *MockPost
}

// NewMockPost creates a new mock instance.
func NewMockPost(ctrl *gomock.Controller) *MockPost {
	mock := &MockPost{ctrl: ctrl}
	mock.recorder = &MockPostMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPost) EXPECT() *MockPostMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPost) CreatePost(arg0 *mongo.Client, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostMockRecorder) CreatePost(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPost)(nil).CreatePost), arg0, arg1, arg2)
}

// DeletePost mocks base method.
func (m *MockPost) DeletePost(arg0 *mongo.Client, arg1 primitive.ObjectID, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockPostMockRecorder) DeletePost(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockPost)(nil).DeletePost), arg0, arg1, arg2, arg3)
}

// ReadPost mocks base method.
func (m *MockPost) ReadPost(arg0 *mongo.Client, arg1 primitive.ObjectID, arg2, arg3 string) (*models.PostDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPost", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*models.PostDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPost indicates an expected call of ReadPost.
func (mr *MockPostMockRecorder) ReadPost(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPost", reflect.TypeOf((*MockPost)(nil).ReadPost), arg0, arg1, arg2, arg3)
}

// UpdatePost mocks base method.
func (m *MockPost) UpdatePost(arg0 *mongo.Client, arg1 primitive.ObjectID, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockPostMockRecorder) UpdatePost(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockPost)(nil).UpdatePost), arg0, arg1, arg2, arg3)
}
