@host = localhost:8088
@contentType = application/json

### Create post
POST http://{{host}}/post/
content-type: {{contentType}}

{
  "content": "my first post",
  "author": "some author"
}

### Get post
GET http://{{host}}/post/<<replace with id>>

### Update post
PUT http://{{host}}/post/<<replace with id>>
content-type: {{contentType}}

{
  "content": "updated post",
  "author": "some author"
}

### Delete post
DELETE http://{{host}}/post/<<replace with id>>

### Create comment
POST http://{{host}}/comment/
content-type: {{contentType}}

{
  "content": "my first comment",
  "author": "some author",
  "postId": "<<replace with post id>>"
}

### Get comment
GET http://{{host}}/comment/<<replace with id>>

### Update comment
PUT http://{{host}}/comment/<<replace with id>>
content-type: {{contentType}}

{
  "content": "updated comment",
  "author": "some author"
}

### Delete comment
DELETE http://{{host}}/comment/<<replace with id>>